### ISSUE TITLE
Rebuild classes from R24 schema

### ISSUE THREAD

**Issue by kikohnl** [nigelm/broadworks_ocip#7]
* Broadworks OCI-P Interface version: R24
* Python version:Python 3.8.10
* Operating System:Ubuntu 20.04.3

### Description

Current Schema is based on R21 we have moved to R24 and would like to rebuild the classes from the R24 schema.

### What I Did

```
Copy the R24 schemas in to ocip_schemaR24
./utilities/process_schema.py -schema ocip_schemaR24
Traceback (most recent call last):
  File "./utilities/process_schema.py", line 11, in <module>
    import xmlschema
ModuleNotFoundError: No module named 'xmlschema'
```

**Comment by nigelm** [comment]
The specific issue you have is that you have not installed the requirements or you are running the code outside the virtual environment that poetry sets up.

The simplest way around this is to use the prebuilt commands in the Makefile.

- Copy the R24 schema files into the `ocip_schema` directory following the same layout as the existing set (overwrite them).
- Ensure that the poetry environment is in place - `poetry install`
- Remove the `schema.pkl` file if it exists - this is a cache file that makes things much faster
- Rebuild the class files - `make code`

This may fail - possibly for trivial reasons (previous versions of schema have had broken BOM or end of file markrers), or possibly because the files are structured differently.

I will see if I can get the R24 schemas and rebuild in the near future, but cannot makr promises as to how quickly.

**Comment by nigelm** [comment]
First attempt is pushed as the r24_bare branch - https://github.com/nigelm/broadworks_ocip/tree/r24_bare

This branch is on top of a whole batch of other changes changing the underlying class system.  This appears to work fine,
but has only been tested against a live system in very basic form - basically just a login and retrieve version data.
However with this and the (sadly undersized) test suite its a pretty good bet that its doing the right thing.

**Comment by kikohnl** [comment]
Some of my utilities work and I still have to migrate more to R24.

Thank you!
